// Code generated by MockGen. DO NOT EDIT.
// Source: task/service/docker/docker.go
//
// Generated by this command:
//
//	mockgen -source=task/service/docker/docker.go -destination=task/service/docker/mock/docker.go -package=dockermock
//

// Package dockermock is a generated GoMock package.
package dockermock
