name: Test 

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      id: cache-modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go modules
      run: |
        go mod tidy
        go mod vendor

    - name: Install gotestsum
      run: |
        go install gotest.tools/gotestsum@latest
        export PATH=$PATH:$(go env GOPATH)/bin

    - name: Run tests with gotestsum
      run: |
        gotestsum --format standard-verbose -- --covermode atomic --coverpkg ./... --count 1 --race ./...
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/
        if-no-files-found: ignore
